# Generated by Django 2.1.7 on 2019-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Component_Type',
            field=models.CharField(blank=True, choices=[('E', 'Electronics'), ('S', 'Storage')], max_length=1),
        ),
        migrations.AddField(
            model_name='items',
            name='Condition',
            field=models.CharField(blank=True, choices=[('U', 'Usable'), ('F', 'faulty')], max_length=1),
        ),
        migrations.AddField(
            model_name='items',
            name='Network_ID',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='items',
            name='component_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
