# Generated by Django 2.1.7 on 2019-03-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compo', '0002_auto_20190319_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'items'},
        ),
        migrations.RemoveField(
            model_name='items',
            name='id',
        ),
        migrations.AlterField(
            model_name='items',
            name='Component_Type',
            field=models.CharField(blank=True, choices=[('L', 'Laptops'), ('S', 'Storage'), ('M', 'Mobiles'), ('F', 'Fashion')], max_length=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='Network_ID',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
    ]
