# Generated by Django 2.1.7 on 2019-03-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compo', '0003_auto_20190320_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='component_name',
            new_name='Component_Name',
        ),
        migrations.AlterField(
            model_name='items',
            name='Component_Type',
            field=models.CharField(blank=True, choices=[('Laptops', 'Laptops'), ('Storage', 'storage'), ('Mobiles', 'Mobiles'), ('Fashion', 'Fashion')], max_length=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='Condition',
            field=models.CharField(blank=True, choices=[('USABLE', 'Usable'), ('FAULTY', 'faulty')], max_length=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='Status',
            field=models.CharField(choices=[('FREE', 'Free'), ('IN USE', 'In use')], max_length=1),
        ),
    ]
